services:
  - type: web
    name: club-compass
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn club_compass.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DJANGO_SETTINGS_MODULE
        value: club_compass.settings
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SITE_ID
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: club-compass.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: club-compass-db
          property: connectionString
    healthCheckPath: /home
    autoDeploy: true

databases:
  - name: club-compass-db
    databaseName: club_compass
    user: club_compass
    plan: free 